# Generated by Django 2.2.4 on 2020-03-18 16:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('willingness_to_act', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='altruism_qual',
        ),
        migrations.AddField(
            model_name='player',
            name='willingness_future',
            field=otree.db.models.StringField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
