# Generated by Django 2.2.4 on 2020-03-18 20:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('willingness_to_act', '0003_auto_20200318_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='willingness_future',
            field=otree.db.models.StringField(choices=[['0', ''], ['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', ''], ['8', ''], ['9', ''], ['10', '']], max_length=10000, null=True, verbose_name=''),
        ),
    ]
