# Generated by Django 2.2.4 on 2020-03-19 09:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('willingness_to_act', '0009_auto_20200319_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='willingness_unfair_others',
            field=otree.db.models.StringField(choices=[['0', ''], ['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', ''], ['8', ''], ['9', ''], ['10', '']], max_length=10000, null=True, verbose_name='\n        How willing are you to punish someone who treats you unfairly, \n        even if there may be costs for you? \n        '),
        ),
        migrations.AlterField(
            model_name='player',
            name='willingness_future',
            field=otree.db.models.StringField(choices=[['0', ''], ['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', ''], ['8', ''], ['9', ''], ['10', '']], max_length=10000, null=True, verbose_name='\n        How willing are you to give up something that is beneficial for you today \n        in order to benefit more from that in the future?\n        '),
        ),
        migrations.AlterField(
            model_name='player',
            name='willingness_unfair',
            field=otree.db.models.StringField(choices=[['0', ''], ['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', ''], ['8', ''], ['9', ''], ['10', '']], max_length=10000, null=True, verbose_name='\n        How willing are you to punish someone who treats you unfairly, \n        even if there may be costs for you? \n        '),
        ),
    ]
