# Generated by Django 2.2.4 on 2020-03-21 18:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('altruism_hypothetical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='altruism',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
