# Generated by Django 2.2.4 on 2020-03-21 18:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('altruism_hypothetical', '0002_player_altruism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='altruism',
        ),
        migrations.AddField(
            model_name='player',
            name='altruism_hypothetical',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
