# Generated by Django 2.2.4 on 2020-03-21 18:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('altruism_hypothetical', '0003_auto_20200321_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='altruism_hypothetical',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
    ]
