# Generated by Django 2.2.4 on 2020-03-21 18:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reciprocity_hypothetical', '0002_player_reciprocity_hypothetical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='reciprocity_hypothetical',
            field=otree.db.models.StringField(choices=[('No present', 'No present'), ('The present worth 5 Euro', 'The present worth 5 Euro'), ('The present worth 10 Euro', 'The present worth 10 Euro'), ('The present worth 15 Euro', 'The present worth 15 Euro'), ('The present worth 20 Euro', 'The present worth 20 Euro'), ('The present worth 25 Euro', 'The present worth 25 Euro'), ('The present worth 30 Euro', 'The present worth 30 Euro')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
